[build]
  command = "npm run build && next export"
  publish = "out"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
